### ISSUE TITLE
`Cannot convert undefined or null to object` while running the pipeline

### ISSUE THREAD

**Issue by kptdobe** [adobe/hypermedia-pipeline#9]
Input md: https://raw.github.com/Adobe-Marketing-Cloud/reactor-user-docs/master/README.md

Full stack: 
```
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at getmetadata (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/@adobe/hypermedia-pipeline/src/html/get-metadata.js:22:23)
    at merge (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/@adobe/hypermedia-pipeline/src/pipeline.js:74:30)
    at tryCatcher (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/reduce.js:157:18)
    at Object.gotAccum (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/alex/work/dev/playground/repos/adobe/helix-helpx/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```

cc @trieloff

**Comment by kptdobe** [comment]
Forgot to mention that this appears in the scope of the helix-cli (when running `hlx up`).
